my code
AlexeyNikitin01/Converter_valute pull request #1
Opened 2021-07-23 21:42 UTC by AlexeyNikitin01

2021-07-23 22:02 UTC, just3mhz requested changes
Потом ещё посмотрю

2021-07-23 22:02 UTC, just3mhz commented on converter_2.py
> +                converter = (1/value["Valute"][self.two_curr]["Value"])*self.money
1) Тут обращение к словарю может выдать исключение.
2) Надо бы в отдельные переменные вынести, очень много кода дублируешь

2021-07-23 22:02 UTC, just3mhz commented on converter_2.py
> +    def converter(self, one_curr, two_curr, money):
Выглядит так, что тут аргументы лишние

2021-07-25 16:27 UTC, AlexeyNikitin01 commented on converter_2.py
> +        self.one_curr = one_curr
можно, но длинно писаться будет, я поэтому поменял.

2021-07-25 16:27 UTC, AlexeyNikitin01 commented on converter_2.py
> +    def currency(self, one_curr, two_curr):
ок

2021-07-25 16:28 UTC, AlexeyNikitin01 commented on converter_2.py
> +        if (self.one_curr in value["Valute"] or self.one_curr == "RUS") and (self.two_curr in value["Valute"] or self.two_curr == "RUS"):
давай)

2021-07-25 16:28 UTC, AlexeyNikitin01 commented on converter_2.py
> +    def input_money(self, money):
что значит отдельная сущность?

2021-07-27 09:44 UTC, just3mhz commented on converter_2.py
> +        self.one_curr = one_curr
Названия очень такие себе. Из названия не очень понятно, о чем речь, да еще и с ошибкой грамматической

2021-07-27 09:53 UTC, just3mhz commented on converter_2.py
> +    def input_money(self, money):
У тебя сейчас весь функционал записан в одном огромном классе, который и считывает валюту, и по api обращается к серверу за курсом валют, и непосредственно перевод. Его бы разбить на отдельные компоненты

2021-07-27 10:06 UTC, just3mhz requested changes

2021-07-27 10:06 UTC, just3mhz commented on converter_2.py
> +                converter = (value["Valute"][self.one_curr]["Value"]/1)*self.money
Деление на 1? Интересно

2021-07-27 10:06 UTC, just3mhz commented on converter_2.py
> +            return False
Либо выше надо True вернуть вместо  `return self.one_curr, self.two_curr`, либо здесь вернуть None

2021-07-27 10:06 UTC, just3mhz commented on converter_2.py
> +            return float(self.money)
Зачем два раза к float приводить?

2021-07-27 10:06 UTC, just3mhz commented on converter_2.py
> +            return False
И опять False зачем-то возвращаешь

2021-07-27 10:06 UTC, just3mhz commented on converter_2.py
> +                converter = self.money
Название переменной - такое себе

2021-07-29 21:27 UTC, AlexeyNikitin01 commented on converter_2.py
> +        self.one_curr = one_curr
Рил ошибка?)

2021-07-29 21:38 UTC, AlexeyNikitin01 commented on converter_2.py
> +    def converter(self, one_curr, two_curr, money):
так если их убрать прога сломается

2021-07-29 21:43 UTC, AlexeyNikitin01 commented on converter_2.py
> +        if self.currency(self.one_curr, self.two_curr) == False:
А как лучше сравнить?

2021-07-29 21:44 UTC, AlexeyNikitin01 commented on converter_2.py
> +                converter = (value["Valute"][self.one_curr]["Value"]/1)*self.money
внатуре)ахахаха, понял

2021-07-29 21:46 UTC, AlexeyNikitin01 commented on converter_2.py
> +            return float(self.money)
первый чтобы проверить, второй вывести.

2021-07-29 21:46 UTC, AlexeyNikitin01 commented on converter_2.py
> +            return False
если тут None вернуть, то при сравнение с None падает

2021-07-29 22:38 UTC, just3mhz requested changes

2021-07-29 22:38 UTC, just3mhz commented on converter.py
> +        if ((self.first_valute in value["Valute"] or self.first_valute == "RUB") and
А зачем тут скобки?

2021-07-29 22:38 UTC, just3mhz commented on converter.py
>      def input_money(self, money):
Тут тоже не используется аргумент money

2021-07-29 22:38 UTC, just3mhz commented on converter.py
> +            elif ((self.first_valute in value["Valute"]) and
Скобки лишние

2021-07-31 17:06 UTC, merged